from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns
import sys


def generate_chart(report_name:str,plot_name:str):
    """@brief Function to generate line chart for the report generated by the sorting program
    """
    
    report = pd.read_csv(f"./data/{report_name}")
    
    report.loc[len(report)] = report.columns
    report.columns =['size','avg_time','avg_comparisons','avg_assignments']
    
    report['size'] = report['size'].astype(int)
    report['avg_time'] = report['avg_time'].astype(float)
    report['avg_comparisons'] = report['avg_comparisons'].astype(float)
    report['avg_assignments'] = report['avg_assignments'].astype(float)
    report = report.sort_values('size')
    
    
    # plotting
    plt.style.use("ggplot")
    plt.style.use("ggplot")
    plt.figure(figsize=(19.2,10.8))

    plt.subplot(2,2,1)
    sns.lineplot(report,x="size",y="avg_time",marker="o")
    plt.legend(["average time"])
    plt.title("AVERAGE TIME")

    plt.subplot(2,2,2)
    sns.lineplot(report,x="size",y="avg_comparisons",color="blue",marker="o")
    plt.legend(["average comparisons"])
    plt.title("AVERAGE COMPARISONS")
    
    plt.subplot(2,2,3)
    sns.lineplot(report,x="size",y="avg_assignments",color="green",marker="o")
    plt.legend(["average comparisons"])
    plt.title("AVERAGE ASSIGNMENTS")

    plt.savefig(f"./charts/{plot_name}")


if(__name__ == "__main__"):
     # get the arguments passed in the command line
    arg_list = sys.argv 
    
    # default value of sort_by_age for the dataset size
    report_name:str = 'sort_by_age_report.csv'
    plot_name:str = 'sort_by_age_plot.png'
    
    if len(arg_list) > 1:
        if type(arg_list[1]) == 'str' and type(arg_list[2]) == 'str':
            report_name = str(arg_list[1])
            plot_name = str(arg_list[2]);
            
    generate_chart(report_name,plot_name)