from matplotlib import pyplot as plt
from pprint import pprint as pp


def generate_chart():
    """@brief Function to generate line chart for the report generated by the sorting program
    """
    str_data = list();
    with open("/home/gaurang/d_drive/College Material/MCA_Sem2/DAA/data/report_insertion_sort.csv","r") as f:
        for line in f:
            str_data.append(line.strip("\n").split(","))
            
    x = [int(row[0]) for row in str_data]
    y = [float(row[1]) for row in str_data]
    
    # plotting
    plt.style.use("ggplot")
    plt.plot(x,y)
    plt.savefig("/home/gaurang/d_drive/College Material/MCA_Sem2/DAA/charts/insertion_sort.png", dpi=300, bbox_inches="tight")
    plt.close()


if(__name__ == "__main__"):
    generate_chart()