from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns


def generate_chart():
    """@brief Function to generate line chart for the report generated by the sorting program
    """
    # str_data = list();
    # with open("/home/gaurang/d_drive/College Material/MCA_Sem2/DAA/data/report_insertion_sort.csv","r") as f:
    #     for line in f:
    #         str_data.append(line.strip("\n").split(","))
            
    # x = [int(row[0]) for row in str_data]
    # y = [float(row[1]) for row in str_data]
    
    report = pd.read_csv('/home/gaurang/d_drive/College Material/MCA_Sem2/DAA/data/report_insertion_sort.csv')
    
    report.loc[len(report)] = report.columns
    report.columns =['size','avg_time','avg_comparisons','avg_assignments']
    
    report['size'] = report['size'].astype(int)
    report['avg_time'] = report['avg_time'].astype(float)
    report['avg_comparisons'] = report['avg_comparisons'].astype(float)
    report['avg_assignments'] = report['avg_assignments'].astype(float)
    report = report.sort_values('size')
    
    
    # plotting
    plt.style.use("ggplot")
    plt.style.use("ggplot")
    plt.figure(figsize=(19.2,10.8))

    plt.subplot(2,2,1)
    sns.lineplot(report,x="size",y="avg_time",marker="o")
    plt.legend(["average time"])
    plt.title("AVERAGE TIME")

    plt.subplot(2,2,2)
    sns.lineplot(report,x="size",y="avg_comparisons",color="blue",marker="o")
    plt.legend(["average comparisons"])
    plt.title("AVERAGE COMPARISONS")
    
    plt.subplot(2,2,3)
    sns.lineplot(report,x="size",y="avg_assignments",color="green",marker="o")
    plt.legend(["average comparisons"])
    plt.title("AVERAGE COMPARISONS")

    plt.savefig('/home/gaurang/d_drive/College Material/MCA_Sem2/DAA/charts/insertion_sort.png')


if(__name__ == "__main__"):
    generate_chart()